### ISSUE TITLE
Expand the description of commands in the devfile

### ISSUE THREAD

**Issue by metlos** [eclipse/che-docs#734]
Currently the description of the commands in the devfile (https://github.com/eclipse/che-docs/blob/master/src/main/pages/che-7/end-user-guide/ref_devfile-reference.adoc#adding-commands-to-a-devfile) lacks the details about the `reference` and `referenceContent` possible there.

These are used to include the IDE specific definitions of commands and therefore represent a quite important usecase, which should be included in the docs.

**Comment by themr0c** [comment]
@metlos Do you men we have an example stating: 

```
 commands:
   - name: build
     actions:
       - type: exec
         component: mysql
         command: mvn clean
         workdir: /projects/spring-petclinic
```

... and we should have an example including the `reference` and `referenceContent` attributes, like that?

```
 commands:
   - name: build
     actions:
       - type: exec
         component: mysql
         command: mvn clean
         workdir: /projects/spring-petclinic
         reference: something
         referenceContent : something
```

Could you help us finding an example that we could user where  `reference` and `referenceContent` are defined?
